### Latent Dirichlet Allocation (LDA).

In [2]:
import pandas as pd

In [3]:
npr = pd.read_csv("npr.csv")

In [4]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [5]:
npr["Article"][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [6]:
npr.head(10)

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...
5  I did not want to join yoga class. I hated tho...
6  With a   who has publicly supported the debunk...
7  I was standing by the airport exit, debating w...
8  If movies were trying to be more realistic, pe...
9  Eighteen years ago, on New Year’s Eve, David F...

In [7]:
len(npr)

11992

## Preprocessing 

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv = CountVectorizer(max_df = 0.95, min_df=2, stop_words="english") 

In [11]:
dtm = cv.fit_transform(npr["Article"])

In [12]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## USE CASE

## LDA

In [15]:
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [17]:
# This can take outlie, we're dealing with a Large amount of documents
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

## Showing Stored Words

In [19]:
len(cv.get_feature_names_out())  # Use get_feature_names_out() instead of get_feature_names()

54777

In [20]:
type(cv.get_feature_names_out())

numpy.ndarray

In [21]:
cv.get_feature_names_out()[50000]

'transcribe'

In [22]:
cv.get_feature_names_out()[20000]

'fungi'

In [23]:
cv.get_feature_names_out()[40000]

'receiving'

In [24]:
import random 

In [25]:
random_word_id = random.randint(0,54777)
print(cv.get_feature_names_out()[random_word_id])

recruiter


In [26]:
for i in range(10):
    random_word_id = random.randint(0, 54777)
    print(cv.get_feature_names_out()[random_word_id])

unevenly
foothills
overprescription
groundnut
respite
omissions
colorado
punchline
bertie
shortbread


## Grab the topics

In [28]:
len(LDA.components_)   

7

In [29]:
LDA.components_.shape

(7, 54777)

In [30]:
len(LDA.components_[0])

54777

In [31]:
single_topic = LDA.components_[0] 

In [32]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [33]:
import numpy as np
                               # This is example of the what is argsort
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [34]:
single_topic.argsort()[-20:]

array([38079, 46581, 48643, 25406, 50426, 10421, 32089, 54403, 18349,
           1, 33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673,
       42561, 42993])

In [35]:
top_word_indices = single_topic.argsort()[-10:]  

In [36]:
for index in  top_word_indices:
    print(cv.get_feature_names_out()[index])    # Loop ke andar har index ka corresponding word print hoga:

new
percent
government
company
million
care
people
health
said
says


## Grab Highest Probability words per topic

In [38]:
from sklearn.decomposition import LatentDirichletAllocation

In [39]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-25:]])  
    print(("\n"))

THE TOP 15 WORDS FOR TOPIC #0
['law', 'plan', 'states', 'business', 'pay', 'president', 'state', 'tax', 'insurance', 'trump', 'companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['russian', 'officials', 'press', 'new', 'country', 'white', 'according', 'attack', 'reported', 'war', 'military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 15 WORDS FOR TOPIC #2
['long', 'small', 'local', 'said', 'life', 'little', 'know', 'don', 'year', 'make', 'way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['researchers', 'drug', 'use', 'brain', 'help', 'world', 'research', 'university', 'percent', 'care', 'time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just

In [40]:
dtm.shape

(11992, 54777)

In [41]:
len(npr)

11992

In [42]:
topic_results = LDA.transform(dtm)

In [43]:
topic_results

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [44]:
topic_results.shape

(11992, 7)

In [45]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [46]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [47]:
topic_results[0].argmax()

1

In [48]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [49]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0])

In [50]:
npr['Topic'] = topic_results.argmax(axis=1)

In [51]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]