# Non-Negative-Matrix-Factorization

In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv("npr.csv")

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
npr["Article"][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

# Preprocessing 

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
# max_df : float in range [0.0, 1.0] or int, default=1.0

In [8]:
# min_df : float in range [0.0, 1.0] or int, default=1

In [9]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words="english")

In [10]:
dtm = tfidf.fit_transform(npr["Article"])

In [11]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## NMF

In [13]:
from sklearn.decomposition import NMF

In [14]:
nmf_model = NMF(n_components=7,random_state=42)

In [15]:
# This can take outile , we're dealing with a large amount of documnets
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

# Diplaying Topics

In [17]:
len(tfidf.get_feature_names_out())

54777

In [18]:
import random 

In [19]:
for i in range (10):
    random_word_id = random.randint(0,54776)
    print(tfidf.get_feature_names_out()[random_word_id])

tempers
bruja
claiming
sebastian
ingredients
fantasy
units
tramadol
pushover
fundraising


In [20]:
len(nmf_model.components_)

7

In [21]:
nmf_model.components_

array([[0.00000000e+00, 2.51270507e-01, 0.00000000e+00, ...,
        1.71376078e-03, 2.39241571e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.23172575e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 3.12287576e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.90615701e-03, 0.00000000e+00, 1.50483058e-03, ...,
        7.06176596e-04, 5.86173445e-04, 6.90910657e-04],
       [4.01955802e-03, 5.31379095e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [22]:
single_topic = nmf_model.components_[0]

In [23]:
# Return the indices that would sort this arrray.
single_topic.argsort()

array([    0, 27208, 27206, ..., 36283, 54692, 42993])

In [24]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([14441, 36310, 53989, 52615, 47218, 53152, 19307, 36283, 54692,
       42993])

In [25]:
top_word_indices = single_topic.argsort()[-10:]

In [26]:
for index in  top_word_indices:
    print(tfidf.get_feature_names_out()[index])

disease
percent
women
virus
study
water
food
people
zika
says


In [55]:
for index, topic in enumerate(nmf_model.components_):
    print(f'THE TOP IS WORDS FOR TOPIC #[index]')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP IS WORDS FOR TOPIC #[index]
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


THE TOP IS WORDS FOR TOPIC #[index]
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


THE TOP IS WORDS FOR TOPIC #[index]
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


THE TOP IS WORDS FOR TOPIC #[index]
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


THE TOP IS WORDS FOR TOPIC #[index]
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


THE TOP IS WORDS FOR TOPI

# Attaching Discovered Topic labels to Original Articles

In [58]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [60]:
dtm.shape

(11992, 54777)

In [62]:
len(npr)

11992

In [71]:
topic_results = nmf_model.transform(dtm)

In [73]:
topic_results.shape

(11992, 7)

In [82]:
topic_results[0]

array([0.        , 0.12079653, 0.00139891, 0.05915242, 0.01519226,
       0.        , 0.        ])

In [84]:
topic_results[0].round(2)

array([0.  , 0.12, 0.  , 0.06, 0.02, 0.  , 0.  ])

In [86]:
topic_results[0].argmax()

1

In [88]:
# This means that out model think that the first article belongs to topics

# Combining with Original Data

In [91]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [93]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3])

In [95]:
npr['Topic'] = topic_results.argmax(axis=1)

In [97]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6
5  I did not want to join yoga class. I hated tho...      5
6  With a   who has publicly supported the debunk...      0
7  I was standing by the airport exit, debating w...      0
8  If movies were trying to be more realistic, pe...      0
9  Eighteen years ago, on New Year’s Eve, David F...      5